archives_application/timekeeper/forms.py
# archives_application/timekeeper/forms.py

from flask_wtf import FlaskForm
from archives_application.models import *
from wtforms import SubmitField, TextAreaField, DateField, SelectField, IntegerField, RadioField, TimeField
from wtforms.validators import DataRequired, Optional, ValidationError

class TimekeepingForm(FlaskForm):
    clock_in = SubmitField('Clock In')
    clock_out = SubmitField('Clock Out')
    clock_out_log_out = SubmitField('Clock Out, Log Out')
    journal = TextAreaField('Journal')


class TimeSheetForm(FlaskForm):
    timesheet_begin = DateField('Timesheet Start', validators=[DataRequired()])
    timesheet_end = DateField('Timesheet End', validators=[DataRequired()])
    rolling_avg_window = IntegerField('Rolling Average Window')
    submit = SubmitField('Submit')

    def validate_timesheet_end(self, timesheet_end):
        if not timesheet_end.data > self.timesheet_begin.data:
            raise ValidationError("Must pick a timesheet start that occurs before the timesheet end.")

    def validate_rolling_avg_window(self, rolling_avg_window):
        if rolling_avg_window.data and rolling_avg_window.data <= 1:
            raise ValidationError("Rolling average window must be greater than 1.")


class TimeKeeperAdminForm(FlaskForm):
    operation = RadioField('Operation', 
                          choices=[('employee_timesheet', 'View Employee Timesheet'), 
                                   ('who_work_when', 'View Who Worked When')],
                          validators=[DataRequired()],
                          default='employee_timesheet')
    employee_email = SelectField('Employee Email')
    selected_date = DateField('Date', validators=[Optional()])  # Add Optional validator
    selected_time = TimeField('Time (optional)', validators=[Optional()])  # Add Optional validator
    submit = SubmitField('Submit')

    def validate(self, extra_validators=None):
        """Custom validation based on selected operation"""
        # Store original validation result but continue execution
        is_valid = super().validate(extra_validators=extra_validators)
        
        # Custom conditional validation
        if self.operation.data == 'who_work_when' and not self.selected_date.data:
            self.selected_date.errors = ["Date is required when viewing who worked when"]
            return False
        
        if self.operation.data == 'employee_timesheet' and not self.employee_email.data:
            self.employee_email.errors = ["Employee email is required when viewing timesheets"]
            return False
        
        # Return the original validation result after applying our custom rules
        return is_valid

archives_application/timekeeper/__init__.py
# archives_application/timekeeper/__init__.py

archives_application/users/routes.py
# archives_application/users/routes.py

import flask
import json
import os
import requests
from flask_login import login_user, logout_user, login_required, current_user
from archives_application import db, bcrypt
from archives_application.models import *
from archives_application import utils
from archives_application.users.forms import *

users = flask.Blueprint('users', __name__)


def get_google_provider_urls():
    """
    This function serves to retrieve the authorization (and other) endpoints from google so they do not have to be
    hard-coded into the application.
    :return: Dictionary of URLs
    """
    g_discovery_url = flask.current_app.config.get('GOOGLE_DISCOVERY_URL')
    response = requests.get(g_discovery_url)
    if not response.status_code == 200:
        raise Exception(
            f"Did not get valid status code from request to {g_discovery_url}\n Got code {response.status_code} instead.")
    return response.json()


def user_login_flow(user):
    login_user(user)
    flask.session[user.email] = {}
    flask.session[user.email]['temporary files'] = []


@users.route("/choose_login")
def choose_login():
    """
    Returns html page where people can choose to login using the google authentication flow or a archives app account
    :return:
    """
    if current_user.is_authenticated:
        flask.flash(f'Already logged in.', 'message')
        return flask.redirect(flask.url_for('main.home'))

    return flask.render_template('choose_login.html', title='Register')


@users.route("/google_auth")
def google_auth():
    """
    Google authentication was created using following tutorial (which needed to be heavily modified to work within this
    application):
    https://realpython.com/flask-google-login/

    :return:
    """
    try:
        authorization_endpoint = get_google_provider_urls()["authorization_endpoint"]
        # Use library to construct the request for Google login and provide
        # scopes that let you retrieve user's profile from Google
        client = flask.current_app.config['google_auth_client']
        request_uri = client.prepare_request_uri(
            authorization_endpoint,
            redirect_uri=flask.request.base_url + "/callback",
            scope=["openid", "email", "profile"],
        )
        return flask.redirect(request_uri)

    except Exception as e:
        return utils.FlaskAppUtils.web_exception_subroutine(
            flash_message="Error during authentication with Google: ",
            thrown_exception=e,
            app_obj=flask.current_app
        )


@users.route("/google_auth/callback")
def callback():
    """
    When Google sends back the unique login code, it’ll be sending it to this login callback endpoint on your application
    :return:
    """

    client = flask.current_app.config['google_auth_client']
    # Get authorization code Google sent back to you
    code = utils.FlaskAppUtils.retrieve_request_param("code")

    #Get token url endpoint
    token_endpoint = get_google_provider_urls()["token_endpoint"]

    # Prepare and send a request to get tokens! Yay tokens!
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=flask.request.url,
        redirect_url=flask.request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(flask.current_app.config['GOOGLE_CLIENT_ID'], flask.current_app.config['GOOGLE_CLIENT_SECRET'])
    )

    try:
        # Parse the tokens!
        client.parse_request_body_response(json.dumps(token_response.json()))

        # Now that you have tokens (yay) let's find and hit the URL
        # from Google that gives you the user's profile information,
        # including their Google profile image and email
        userinfo_endpoint = get_google_provider_urls()["userinfo_endpoint"]
        uri, headers, body = client.add_token(userinfo_endpoint)
        userinfo_response = requests.get(uri, headers=headers, data=body)

        # You want to make sure their email is verified.
        # The user authenticated with Google, authorized your
        # app, and now you've verified their email through Google!
        users_email, first_name, last_name = "","",""
        if userinfo_response.json().get("email_verified"):
            users_email = userinfo_response.json()["email"]
        else:
            flask.flash(f'User email not available or not verified by Google.', 'warning')
            return flask.redirect(flask.url_for('main.home'))

        # Check if email is included in unsanctioned accounts...
        #TODO add unsanctioned accounts to config?
        unsanctioned_accounts = ["test@ucsc.edu", "archives@ucsc.edu", "constdoc@ucsc.edu"]
        if users_email.lower() in unsanctioned_accounts:
            message = f'Account {users_email} is not permitted for Google Authentication.  Sign in with application password or contact application admin.'
            flask.flash(message, 'danger')
            return flask.redirect(flask.url_for('main.home'))

        # Determine if the user is in the database. If not we add them to database
        user = UserModel.query.filter_by(email=users_email).first()
        if not user:
            flask.session['new user'] = {"email": users_email}
            return flask.redirect(flask.url_for('users.google_register'))

        # if there is already an account but it is not an active account...
        if user and not user.active:
            flask.flash(f'Account is inactive. Contact application admin.', 'danger')
            return flask.redirect(flask.url_for('main.home'))

        user_login_flow(user)
        flask.flash("Login Successful.", 'success')
        return flask.redirect(flask.url_for('main.home'))

    except Exception as e:
        return utils.FlaskAppUtils.web_exception_subroutine(
            flash_message='Error during Google Authentication Callback: ',
            thrown_exception=e,
            app_obj=flask.current_app
        )

@users.route("/google_auth/register", methods=['GET', 'POST'])
def google_register():
    # if this endpoint was called without first doing the google Oauth dance
    if not flask.session.get('new user'):
        flask.flash(f'Authenticate via Google Oauth before registering Google account.', 'warning')
        return flask.redirect(flask.url_for('main.home'))
    new_user_email = flask.session['new user']['email']
    form = GoogleRegisterForm()

    # cannot use flask.current_form in the form definition. Hence...
    form.roles.choices = flask.current_app.config.get('ROLES')

    if form.validate_on_submit():
        try:
            user_roles = ",".join(form.roles.data)
            user = UserModel(email=new_user_email, first_name=form.first_name.data, active=True,
                             last_name=form.last_name.data, roles=user_roles)
            db.session.add(user)
            db.session.commit()
            user = UserModel.query.filter_by(email=new_user_email).first()
            user_login_flow(user=user)
            flask.flash(f'Account created for {new_user_email}!', 'success')
            return flask.redirect(flask.url_for('main.home'))
        except Exception as e:
            return utils.FlaskAppUtils.web_exception_subroutine(
                flash_message="Error while initiating google registration workflow: ",
                thrown_exception=e,
                app_obj=flask.current_app
            )

    return flask.render_template('google_register.html', title='Register', form=form)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flask.flash(f'Already logged in.', 'message')
        return flask.redirect(flask.url_for('main.home'))

    return flask.render_template('choose_registration.html', title='Register')


@users.route("/new_account_registeration", methods=['GET', 'POST'])
def new_account_registeration():
    """
    This endpoint is for creating and processing a form for creating a new account that does not use google authentication
    :return:
    """
    # if the current user has already been authenticated, just send them to the home page.
    if current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))

    form = RegistrationForm()

    # cannot use flask.current_form in the form definition. Hence...
    form.roles.choices = flask.current_app.config.get('ROLES')

    if form.validate_on_submit():
        try:
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            db_user = UserModel.query.filter_by(email=form.email.data).first()
            if db_user:
                flask.flash(f'''An account already exists for the email "{form.email.data}"''', 'warning')
                return flask.redirect(flask.url_for('main.home'))
            user_roles = ",".join(form.roles.data)
            user = UserModel(email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data,
                             roles=user_roles, active=True, password=hashed_password)
            db.session.add(user)
            db.session.commit()
            flask.flash(f'Account created for {form.email.data}!', 'success')
            return flask.redirect(flask.url_for('users.login'))

        except Exception as e:
            return utils.FlaskAppUtils.web_exception_subroutine(
                flash_message="Error occured while creating a new account:",
                thrown_exception=e,
                app_obj=flask.current_app
            )

    return flask.render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    # if the current user has already been authenticated, just send them to the home page.
    if current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))

archives_application/templates/batch_change.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" id="batch-server-edit-form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Batch Server Edit</legend>
                <p>This form is for moving the entire contents of one directory into another directory.</br>Depending on the number and size of the target contents files, it can take some time to move all the files.While the application is moving the files it is important to stay out of the way -- not open or otherwise manipulate the files being used by the application while it is doing the batch moving.</p>
                <div class="form-group">
                    <h5>{{ form.asset_path.label(class="form-control-label") }}</h5>
                    <p>This is the path to the folder with the contents that needs to be moved.</p>
                    {% if form.asset_path.errors %}
                        {{ form.asset_path(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.asset_path.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.asset_path(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <h5>{{ form.destination_path.label(class="form-control-label") }}</h5>
                    <p>The path to the destination directory where target directory contents will be moved.</p>
                    {% if form.destination_path.errors %}
                        {{ form.destination_path(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.destination_path.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.destination_path(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="custom-control custom-checkbox">
                        {{ form.remove_asset(class="custom-control-input") }}
                        {{ form.remove_asset.label(class="custom-control-label") }}
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info", id="execute-button") }}
            </div>
        </form>
    </div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var form = document.getElementById('batch-server-edit-form');
        if (form) {
            form.addEventListener('submit', function(event) {
                var button = document.getElementById('execute-button');
                if (button) {
                    button.value = 'Executing...';  // Change button text
                    // Disable button to prevent double submission
                    setTimeout(() => button.disabled = true, 10);
                }
                // Delay form submission to allow button text change
                event.preventDefault();
                setTimeout(() => HTMLFormElement.prototype.submit.call(form), 500);
            });
        }
    });
</script>
{% endblock content %}

archives_application/templates/batch_process_inbox.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <h2>Batch Process Inbox</h2>
  <p>Select the files to archive and provide the required metadata to archive them. All the files will use their current filename.</p>
  <p><a href="https://docs.google.com/document/d/1Xub4G7-STdRrQsmfLbzuJsgFqC9Zu42qeYVMNM87JXM/edit?usp=sharing">Large Format Archiving Documentation.</a></p>
  <p><a href="https://docs.google.com/document/d/1Bu4T71ge-00dWURt_oQHZJZhrLer9Q_bJ-m4xdXcJtI/edit?usp=sharing">Small Format Archiving Documentation.</a></p>
  <form method="POST" action="" id="archive-form-main">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Inbox Files</legend>
      {% for subfield in form.items_to_archive %}
      <div class="form-check">
        {{ subfield(class="form-check-input") }}
        {{ subfield.label(class="form-check-label") }}
      </div>
      {% endfor %}
    </fieldset>
    <fieldset class="form-group">
      <h6>Either enter a...</h6>
      <legend class="border-bottom mb-4">Archiving Information</legend>
      <div class="form-group">
        <h5>{{ form.project_number.label(class="form-control-label") }}</h5>
        {% if form.project_number.errors %}
          {{ form.project_number(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.project_number.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.project_number(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <h6>..and choose a...</h6>
      <div class="form-group">
        <h5>{{ form.destination_directory.label(class="form-control-label") }} (Filing Code)</h5>
        {% if form.destination_directory.errors %}
          {{ form.destination_directory(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.destination_directory.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.destination_directory(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <h6>...or, alternatively, enter path to archiving destination directory:</h6>
      <div class="form-group">
        <h5>{{ form.destination_path.label(class="form-control-label") }} (Optional)</h5>
        <p>Useful for archiving to a location that doesn't have a corresponding project or if it needs custom directory structure beyond the filing code directories.</p>
        {% if form.destination_path.errors %}
          {{ form.destination_path(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.destination_path.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.destination_path(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        <h5>{{ form.notes.label(class="form-control-label") }} (Optional)</h5>
        <p>Notes entered here will be associated wilth all archived files in the batch.</p>
        {% if form.notes.errors %}
          {{ form.notes(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.notes.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.notes(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <p>Make sure none of the files to be archived are open in other programs before submitting.</p>
    <div class="form-group">
      <input type="submit" class="btn btn-outline-info" value="Archive Selected Files" id="archive-button">
    </div>
  </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var archiveForm = document.getElementById('archive-form-main');
        if (archiveForm) {
            archiveForm.addEventListener('submit', function(event) {
                var button = document.getElementById('archive-button');
                if (button) {
                    button.value = 'Archiving...';  // Change button text
                    // Disable button to prevent double submission
                    setTimeout(() => button.disabled = true, 10);
                }
                // Delay form submission to allow button text change
                event.preventDefault();
                setTimeout(() => HTMLFormElement.prototype.submit.call(archiveForm), 500);
            });
        }
    });
</script>
{% endblock content %}

archives_application/templates/caan_drawings.html
{% set hide_sidebar = True %}
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h2>Projects associated with CAAN {{ caan }}, {{ caan_name }}</h2>
        <div>
            <p>
                This page lists projects and their respective locations on the archives server.<br>
                The project data is pulled from the FileMaker database; therefore, its accuracy depends on the data stored there.<br>
                The locations shown are paths to project directories on the archives server and, given the current organization of those files and folders, represent the closest likely location of the project drawing files.<br>
                Copy and paste a location into a web or file browser address bar.
            </p>
        </div>
            
        <div>
            <!-- If there is a result table, display it here. -->
            {% if drawings_confirmed_table %}
                <h4>Projects that have drawings</h4>
                <p>Projects confirmed to have drawings (per FileMaker entry).</p>
                {{ drawings_confirmed_table | safe }}
            {% endif %}
            {% if drawings_maybe_table %}
                <hr>
                <h4>Projects that might have drawings</h4>
                <p>Projects where the "drawings" attribute is blank in FileMaker.</p>
                {{ drawings_maybe_table | safe }}
            {% endif %}
        </div>
    </div>
{% endblock content %}

archives_application/templates/caan_search_results.html
{% set hide_sidebar = True %}
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
	<h2>CAAN Search Results</h2>
	<p>
		<a href="{{ url_for('project_tools.caan_search') }}" class="btn btn-sm btn-secondary">New Search</a>
	</p>
	{% if query %}
		<p>Search terms: <strong>{{ query }}</strong></p>
	{% endif %}
	{% if table_list %}
	<div class="table-responsive">
		<table class="table table-sm table-striped table-hover">
			<thead class="thead-light">
				<tr>
					<th style="width:10%">CAAN</th>
					<th style="width:25%">Name</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
			{% for row in table_list %}
				<tr>
					<td><a href="{{ url_for('project_tools.caan_drawings', caan=row.caan) }}">{{ row.caan }}</a></td>
					<td>{{ row.name }}</td>
					<td>{{ row.description }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	<p class="text-muted">{{ table_list|length }} result{{ '' if table_list|length == 1 else 's' }}.</p>
	{% else %}
		<p>No results.</p>
	{% endif %}
</div>
{% endblock content %}

archives_application/templates/change_config_settings.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Settings to Change</legend>
                <p>Use this form to change application configuration values. Anything entered here will overwrite the corresponding contents of the config file. The application will restart before changes take effect.</p>
                {% for setting, _ in settings_dict.items() %}
                    <div class="form-group">
                        <!-- Setting field -->
                        <h6>{{ form[setting].label (class="form-control-label") }}</h6>
                        {% if settings_dict[setting]["DESCRIPTION"] %}
                            <p>Description: {{ settings_dict[setting]["DESCRIPTION"] }}</p>
                        {% endif %}
                        {% if form[setting].errors %}
                            {{ form[setting](class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form[setting].errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form[setting](class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                {% endfor %}
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

archives_application/templates/choose_login.html
{% extends "layout.html" %}
{% block content %}
    <div class="border-top pt-3">
        <p>
                 <a class="ml-2" href="{{ url_for('users.login') }}">Use Application Sign-In</a>
        </p>
    </div>
    <div class="border-top pt-3">
        <p>
                 <a class="ml-2" href="{{ url_for('users.google_auth') }}">Sign In with Google</a>
        </p>
    </div>
{% endblock content %}

archives_application/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <h2>Welcome!</h2>
      <p>
          This is the archives app and serves as an application layer for our document file server (aka "PPDO\Records"). You can use this app to search and manage documents stored on the file server. 
      </p>
    </div>
{% endblock content %}

archives_application/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                    <a href="#">Forgot password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

archives_application/templates/scrape_location.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Scrape File Data</legend>
                <p>This tool reconciles discrepancies between the file server and this application's database. It is useful for recording changes made directly on the file server (e.g., via Windows Explorer).</p>
                <div class="form-group">
                    <h6>{{ form.scrape_location.label(class="form-control-label") }}</h6>
                    <p>(Case sensitive. Copy this from the Windows File Explorer address bar.)</p>
                    {% if form.scrape_location.errors %}
                        {{ form.scrape_location(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.scrape_location.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.scrape_location(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                     <h6>{{ form.recursive.label(class="form-control-label") }}</h6>
                    <p>A recursive search will include all nested directories within the specified location.</p>
                        {% if form.recursive.errors %}
                            {{ form.recursive(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.recursive.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.recursive(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}